''
'' Nik'S Default theme
''
'' Author: Nik Khilnani
'' Copyright (c) 2023 by Nik Khilnani

!$THEME = "default"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

!$BLACK = "#111111"
!$WHITE = "#fff"
!$GREEN = "#00FF00"
!$RED = "#D30000"
!$ARROW = "#999999"
!$BORDER = "#666666"
!$BORDER_LIGHT = "#AAAAAA"

!$TEXT = "#444444"
!$TEXT_FONT = "Helvetica"
!$TEXT_STYLE = "normal"
!$TEXT_SMALL_SIZE = "10"
!$TEXT_SIZE = "12"
!$TEXT_LARGE_SIZE = "14"
!$TEXT_XLARGE_SIZE = "18"
!$TEXT_ALIGN = "center"

!$MARGIN = "8"
!$PADDING = "10"
!$CORNER_RADIUS = "10"

!$LINE_THIN = "0.5"
!$LINE = "1"
!$LINE_THICK = "1.5"
!$LINE_XTHICK = "3"

!$DIVIDER_DARK = "#666666"
!$DIVIDER_LIGHT = "#AAAAAA"

!$GREY_LIGHT = "#f6f6f6/f3f3f3"
!$GREY = "999999"
!$GREY_DARK = "#333333"

!$BLUE_LIGHT_DARK = "#CEDBE1"
!$BLUE_LIGHT_LIGHT = "#edf5f9"

!$YELLOW_TEXT = "#5F560B"
!$YELLOW_DARK = "#C8B609"
!$YELLOW = "#fff166"
!$YELLOW_LIGHT = "#f9f9f9"

!$PURPLE_DARK = "#3E4681"

!$BLUE_DARK = "#6998B5"
!$BLUE_LIGHT = "#A9CCE3"

skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false
skinparam componentStyle uml2
skinparam monochrome false
skinparam shadowing false
skinparam roundCorner $CORNER_RADIUS

skinparam Arrow {
    Color $ARROW
    Thickness $LINE
    ArrowMessageAlign center
}

skinparam default {
    BorderColor $BORDER
    FontColor $TEXT
    FontName $TEXT_FONT
    FontSize $TEXT_SIZE
    TextAlignment $TEXT_ALIGN
}

skinparam legend {
	BackgroundColor $GREY_LIGHT
	BorderColor $GREY
	FontColor $TEXT
    FontSize $TEXT_SIZE
}

skinparam Box {
    Padding $PADDING
    BorderThickness $LINE
    BorderColor $BLUE_LIGHT_DARK
    BackgroundColor $BLUE_LIGHT_LIGHT
}

skinparam Note {
    FontColor $YELLOW_TEXT
    BorderThickness $LINE
    BorderColor $YELLOW_DARK
    BackgroundColor $YELLOW
}

skinparam Participant {
    Padding 20
    BorderThickness $LINE_THICK
    FontColor $PURPLE_DARK
    BackgroundColor $WHITE
    BorderColor $PURPLE_DARK 
}

skinparam sequence {

    ArrowColor $ARROW

    LifeLineBorderThickness $LINE
    LifeLineBorderColor $BLUE_DARK
    LifeLineBackgroundColor $BLUE_LIGHT
    
    BoxPadding $PADDING
    BoxBorderThickness $LINE
    BoxBorderColor $BLUE_LIGHT_DARK
    BoxBackgroundColor $BLUE_LIGHT_LIGHT

    DividerBorderColor $DIVIDER_DARK
    DividerBorderThickness $LINE
    DividerBackgroundColor $DIVIDER_LIGHT
    
    GroupBorderColor $YELLOW_DARK
    GroupBorderThickness $LINE
    GroupBackgroundFontColor $YELLOW_TEXT
    GroupBackgroundColor $YELLOW
    
    GroupBodyFontColor $YELLOW_DARK
    GroupBodyBackgroundColor $YELLOW_LIGHT
}

skinparam Rectangle {
    Padding $PADDING
    BorderThickness $LINE
    BackgroundColor $GREY_LIGHT
    StereotypeFontColor $BLUE_DARK
}

skinparam package {
    BackgroundColor $BLUE_LIGHT_LIGHT
    BorderColor $BLUE_DARK
    BorderThickness $LINE
    TitleAlignment "left"
    FontColor $TEXT
    StereotypeFontColor $BLUE_DARK
}

skinparam frame {
    BackgroundColor $BLUE_LIGHT_LIGHT
    BorderColor $BLUE_DARK
    BorderThickness $LINE
    TitleAlignment "left"
    FontColor $TEXT
    StereotypeFontColor $BLUE_DARK
}

skinparam folder {
    BackgroundColor $BLUE_LIGHT_LIGHT
    BorderColor $BLUE_DARK
    BorderThickness $LINE
    TitleAlignment "left"
    FontColor $TEXT
    StereotypeFontColor $BLUE_DARK
}

skinparam class {
    BorderThickness $LINE
    BackgroundColor $GREY_LIGHT
}

skinparam Database {
    BorderThickness $LINE
    BackgroundColor $GREY_LIGHT
}

skinparam Control {
    BorderThickness $LINE
    BackgroundColor $GREY_LIGHT
}

skinparam Entity {
    BorderThickness $LINE
    BackgroundColor $GREY_LIGHT
}

skinparam Boundary {
    BorderThickness $LINE
    BackgroundColor $GREY_LIGHT
}

skinparam Actor {
    Style awesome
    BorderColor $PURPLE_DARK
    BorderThickness $LINE_XTHICK
    BackgroundColor $WHITE
    FontColor $PURPLE_DARK
}

skinparam usecase {
    BackgroundColor $WHITE
    BorderThickness $LINE    
    FontColor $TEXT
    BorderColor $GREY
    StereotypeFontColor $GREY_DARK
    StereotypeFontSize $TEXT_SMALL_SIZE
    StereotypeFontStyle "italic"
}

skinparam Group {
    FontColor $YELLOW_TEXT
    BodyFontColor $YELLOW_TEXT
    BorderColor $YELLOW_DARK
    BorderThickness 1
    BackgroundFontColor $YELLOW_TEXT
    BackgroundColor $YELLOW
    BodyBackgroundColor $YELLOW_LIGHT
}

skinparam Collections {
    BorderThickness $LINE
    BackgroundColor $GREY_LIGHT
}


skinparam state {
    AttributeFontColor $ARROW
    AttributeFontSize $TEXT_SMALL_SIZE
    BackgroundColor $BLUE_LIGHT_LIGHT
    BorderColor $BORDER
    FontColor $TEXT
    FontSize $TEXT_SIZE
    FontStyle "bold"
    StartColor $GREEN
    EndColor $RED
}

skinparam activity {
  BorderThickness $LINE
  BorderColor $BLUE_DARK
  BackgroundColor $BLUE_LIGHT
  BarColor $ARROW
}

skinparam activityDiamond {
    BackgroundColor $YELLOW_LIGHT
    BorderColor $YELLOW_DARK
    FontSize $TEXT_LARGE_SIZE
}

skinparam swimlane {
	BorderColor $BORDER_LIGHT
  BorderThickness $LINE_THIN
  TitleFontSize $TEXT_XLARGE_SIZE
  TitleBackgroundColor $WHITE
  TitleFontStyle "bold"
}

skinparam partition {
  BorderThickness $LINE_THIN
	BorderColor $BLUE_DARK
	FontColor $BLUE_DARK
	BackgroundColor $BLUE_LIGHT_LIGHT
}

<style>

wbsDiagram, mindmapDiagram {
  Padding $PADDING
  Margin $MARGIN
  LineThickness $LINE
  FontColor $TEXT
  LineColor $ARROW
  Roundcorner $CORNER_RADIUS
  node {
    Padding $PADDING
    Margin $MARGIN
    HorizontalAlignment $TEXT_ALIGN
    LineColor $BORDER
    LineThickness $LINE
    BackgroundColor $BLUE_LIGHT_LIGHT
    Roundcorner $CORNER_RADIUS
    MaximumWidth 100
    FontColor $TEXT
    FontStyle $TEXT_STYLE
  }
  rootNode {
    LineStyle 2
  }
}

</style>
